#!/bin/sh
# php-fpm ping ucunu cgi-fcgi ile sorgular (fcgi paketi gerekir)
set -eu

export SCRIPT_NAME=/ping
export SCRIPT_FILENAME=/ping
export REQUEST_METHOD=GET

cgi-fcgi -bind -connect 127.0.0.1:9000 | grep -q pong
